CXX = $(shell root-config --cxx 2>/dev/null)
CXXFLAGS = $(shell root-config --cflags 2>/dev/null) -std=c++17 -Wall -Wextra -O3 -fopenmp -fPIC
ROOTLIBS = $(shell root-config --glibs 2>/dev/null) -lRooFit -lRooFitCore -fopenmp
# Directories
SRCDIR = src
INCDIR = include
OBJDIR = obj
LIBDIR = lib
# Source files
SOURCES = $(wildcard $(SRCDIR)/*.cpp)
OBJECTS = $(SOURCES:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)
HEADERS = $(wildcard $(INCDIR)/*.hpp)
# Library name
LIBNAME = lib-analysis-utils

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
  SHAREDLIB_NAME = $(LIBNAME).dylib
  SHARED_FLAGS = -dynamiclib
else
  SHAREDLIB_NAME = $(LIBNAME).so
  SHARED_FLAGS = -shared
endif
SHAREDLIB = $(LIBDIR)/$(SHAREDLIB_NAME)

# Custom RooAbsPdf classes need a ROOT dictionary generated by rootcling
DICT_HEADERS = $(INCDIR)/RooFitPhotopeakPdfs.hpp
DICT_LINKDEF = $(INCDIR)/LinkDef.h
DICT_CXX = $(OBJDIR)/$(LIBNAME)Dict.cxx
DICT_OBJ = $(OBJDIR)/$(LIBNAME)Dict.o
DICT_PCM = $(LIBDIR)/$(LIBNAME)_rdict.pcm
DICT_ROOTMAP = $(LIBDIR)/$(LIBNAME).rootmap

STATICLIB = $(LIBDIR)/$(LIBNAME).a
# Default target - build both shared and static libraries
all: $(SHAREDLIB) $(STATICLIB)
# Create directories
$(OBJDIR):
	mkdir -p $(OBJDIR)
$(LIBDIR):
	mkdir -p $(LIBDIR)
# Compile object files
$(OBJDIR)/%.o: $(SRCDIR)/%.cpp $(HEADERS) | $(OBJDIR)
	$(CXX) $(CXXFLAGS) -I$(INCDIR) -c $< -o $@
# Generate ROOT dictionary for custom RooAbsPdf classes
$(DICT_CXX): $(DICT_HEADERS) $(DICT_LINKDEF) | $(OBJDIR) $(LIBDIR)
	cd $(INCDIR) && rootcling -f ../$@ -s ../$(LIBDIR)/$(LIBNAME) -rml $(SHAREDLIB_NAME) -rmf ../$(DICT_ROOTMAP) $(notdir $(DICT_HEADERS)) $(notdir $(DICT_LINKDEF))
$(DICT_OBJ): $(DICT_CXX)
	$(CXX) $(CXXFLAGS) -I$(INCDIR) -c $< -o $@
# Create shared library (with dictionary)
$(SHAREDLIB): $(OBJECTS) $(DICT_OBJ) | $(LIBDIR)
	$(CXX) $(SHARED_FLAGS) -o $@ $^ $(ROOTLIBS)
	@echo "Built shared library: $(SHAREDLIB)"
# Dictionary lives only in the .so; bundling it here too would risk double TClassTable registration if a downstream links both
$(STATICLIB): $(OBJECTS) | $(LIBDIR)
	ar rcs $@ $^
	@echo "Built static library: $(STATICLIB)"
PREFIX ?= /usr/local

install: $(SHAREDLIB) $(STATICLIB)
	install -d $(PREFIX)/lib $(PREFIX)/include $(PREFIX)/lib/pkgconfig
	install -m755 $(SHAREDLIB) $(PREFIX)/lib/
	install -m644 $(STATICLIB) $(PREFIX)/lib/
	install -m644 $(HEADERS) $(PREFIX)/include/
	install -m644 $(DICT_PCM) $(PREFIX)/lib/
	install -m644 $(DICT_ROOTMAP) $(PREFIX)/lib/
	sed -e 's|@PREFIX@|$(PREFIX)|g' \
	    -e 's|@LIBNAME@|$(LIBNAME)|g' \
	    analysis-utilities.pc.in > $(PREFIX)/lib/pkgconfig/analysis-utilities.pc
clean:
	rm -rf $(OBJDIR) $(LIBDIR)

# API documentation — the plain-make counterpart of the CMake `docs` target.
# flake.nix stays the canonical version source, parsed here the same way that
# CMakeLists.txt parses it rather than keeping a second copy that drifts.
DOCSDIR = docs
AU_VERSION = $(shell sed -n 's/^ *version = "\([^"]*\)"; *$$/\1/p' flake.nix | head -1)
AU_HAVE_DOT = $(shell command -v dot >/dev/null 2>&1 && echo YES || echo NO)
# doxygen-awesome-css is data-only, so it is located by env var rather than
# PATH. Both dev shells export DOXYGEN_AWESOME_CSS.
AU_AWESOME_DIR ?= $(DOXYGEN_AWESOME_CSS)

docs: Doxyfile.in
	@command -v doxygen >/dev/null 2>&1 || \
	  { echo "doxygen not found - enter the dev shell first with 'nix develop'"; exit 1; }
	@test -f "$(AU_AWESOME_DIR)/doxygen-awesome.css" || \
	  { echo "doxygen-awesome-css not found - set DOXYGEN_AWESOME_CSS or run inside 'nix develop'"; exit 1; }
	@mkdir -p $(DOCSDIR)
	sed -e 's|@AU_VERSION@|$(AU_VERSION)|g' \
	    -e 's|@AU_SOURCE_DIR@|$(CURDIR)|g' \
	    -e 's|@AU_DOXYGEN_OUTPUT_DIR@|$(CURDIR)/$(DOCSDIR)|g' \
	    -e 's|@AU_DOXYGEN_HAVE_DOT@|$(AU_HAVE_DOT)|g' \
	    -e 's|@AU_DOXYGEN_AWESOME_DIR@|$(AU_AWESOME_DIR)|g' \
	    Doxyfile.in > $(DOCSDIR)/Doxyfile
	doxygen $(DOCSDIR)/Doxyfile
	@echo "API documentation: $(CURDIR)/$(DOCSDIR)/html/index.html"
	@echo "Doxygen warnings:  $(CURDIR)/$(DOCSDIR)/doxygen-warnings.log"

# Kept out of `clean` so that rebuilding the library does not quietly discard a
# generated doc tree someone has open in a browser.
clean-docs:
	rm -rf $(DOCSDIR)

.PHONY: all install clean docs clean-docs
