CXX = $(shell root-config --cxx)
CXXFLAGS = $(shell root-config --cflags) -std=c++17 -Wall -Wextra -O2 -fPIC
ROOTLIBS = $(shell root-config --glibs) -lRooFit -lRooFitCore
# Directories
SRCDIR = src
INCDIR = include
OBJDIR = obj
LIBDIR = lib
# Source files
SOURCES = $(wildcard $(SRCDIR)/*.cpp)
OBJECTS = $(SOURCES:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)
HEADERS = $(wildcard $(INCDIR)/*.hpp)
# Library name
LIBNAME = lib-analysis-utils

# Custom RooAbsPdf classes need a ROOT dictionary generated by rootcling
DICT_HEADERS = $(INCDIR)/RooFitPhotopeakPdfs.hpp
DICT_LINKDEF = $(INCDIR)/LinkDef.h
DICT_CXX = $(OBJDIR)/RooFitPhotopeakPdfsDict.cxx
DICT_OBJ = $(OBJDIR)/RooFitPhotopeakPdfsDict.o
DICT_PCM = $(LIBDIR)/RooFitPhotopeakPdfsDict_rdict.pcm

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
  SHAREDLIB = $(LIBDIR)/$(LIBNAME).dylib
  SHARED_FLAGS = -dynamiclib
else
  SHAREDLIB = $(LIBDIR)/$(LIBNAME).so
  SHARED_FLAGS = -shared
endif

STATICLIB = $(LIBDIR)/$(LIBNAME).a
# Default target - build both shared and static libraries
all: $(SHAREDLIB) $(STATICLIB)
# Create directories
$(OBJDIR):
	mkdir -p $(OBJDIR)
$(LIBDIR):
	mkdir -p $(LIBDIR)
# Compile object files
$(OBJDIR)/%.o: $(SRCDIR)/%.cpp $(HEADERS) | $(OBJDIR)
	$(CXX) $(CXXFLAGS) -I$(INCDIR) -c $< -o $@
# Generate ROOT dictionary for custom RooAbsPdf classes
$(DICT_CXX): $(DICT_HEADERS) $(DICT_LINKDEF) | $(OBJDIR) $(LIBDIR)
	cd $(INCDIR) && rootcling -f ../$@ -s ../$(LIBDIR)/RooFitPhotopeakPdfsDict -rmf ../$(LIBDIR)/RooFitPhotopeakPdfsDict.rootmap $(notdir $(DICT_HEADERS)) $(notdir $(DICT_LINKDEF))
$(DICT_OBJ): $(DICT_CXX)
	$(CXX) $(CXXFLAGS) -I$(INCDIR) -c $< -o $@
# Create shared library (with dictionary)
$(SHAREDLIB): $(OBJECTS) $(DICT_OBJ) | $(LIBDIR)
	$(CXX) $(SHARED_FLAGS) -o $@ $^ $(ROOTLIBS)
	@echo "Built shared library: $(SHAREDLIB)"
# Create static library
$(STATICLIB): $(OBJECTS) $(DICT_OBJ) | $(LIBDIR)
	ar rcs $@ $^
	@echo "Built static library: $(STATICLIB)"
PREFIX ?= /usr/local

install: $(SHAREDLIB) $(STATICLIB)
	install -d $(PREFIX)/lib $(PREFIX)/include $(PREFIX)/lib/pkgconfig
	install -m755 $(SHAREDLIB) $(PREFIX)/lib/
	install -m644 $(STATICLIB) $(PREFIX)/lib/
	install -m644 $(HEADERS) $(PREFIX)/include/
	install -m644 $(LIBDIR)/RooFitPhotopeakPdfsDict_rdict.pcm $(PREFIX)/lib/ || true
	install -m644 $(LIBDIR)/RooFitPhotopeakPdfsDict.rootmap $(PREFIX)/lib/ || true
	sed -e 's|@PREFIX@|$(PREFIX)|g' \
	    -e 's|@LIBNAME@|$(LIBNAME)|g' \
	    analysis-utilities.pc.in > $(PREFIX)/lib/pkgconfig/analysis-utilities.pc
clean:
	rm -rf $(OBJDIR) $(LIBDIR)
.PHONY: all install clean
